version: '3.8'

services:
  uni-dashboard-staging:
    image: ${DOCKER_REGISTRY}/uni-dashboard:${VERSION}
    # container_name: uni-dashboard-staging
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - uni-dashboard-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 0
        order: stop-first

networks:
  uni-dashboard-network:
    driver: bridge 